
export const UPDATE_LYRIC = 'UPDATE_LYRIC';
export const UPDATE_LYRIC_PERCENT = 'UPDATE_LYRIC_PERCENT';
export const UPDATE_SONG_DURATION = 'UPDATE_SONG_DURATION';
export const UPDATE_SONG_CURRENT_TIME = 'UPDATE_SONG_CURRENT_TIME';
export const UPDATE_PLAYED_PERCENT = 'UPDATE_PLAYED_PERCENT';
export const FULLFILL_SEEKBAR = 'FULLFILL_SEEKBAR';
export const UNFULLFILL_SEEKBAR = 'UNFULLFILL_SEEKBAR';

export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';

